In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  # Create a rank 1 array
print (type(a))            # Prints "<type 'numpy.ndarray'>"
print (a.shape)            # Prints "(3,)"
#print (a[0], a[1], a[2])   # Prints "1 2 3"
print(a[0])                # Change an element of the array
print (a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3, 3)
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import pandas as pd
df2 = pd.DataFrame({ 'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                   'D' : np.array([3] * 4,dtype='int32'),
                   'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [4]:
df2[0:3]

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo